### PR TITLE
8 byte alignment in image_sizing

### LINKED ISSUE #50: (Unnamed) semaphore issues when  using ISIO through pybind.
Hey guys - in particular @a-sevin and @drbitboy .

TLDR: see other comments below. It's 4-byte alignement at work.

Since merging Brian's PR #40 and transitioning to embedded semaphores, I'm having a misbehavior when calling SHMs through pyMilk/ImageStreamIOWrap.
Calling a semwait upon a semaphore that's not immediately passing (i.e., sem == 0) causes a futex crash.
Unclear to me what the heck is going on... here's a minimum crashing example.

```python
import numpy as np
from ImageStreamIOWrap import Image
print('Create')
img = Image()
img.create('something', np.array([0], np.uint16), location=-1, shared=1, NBkw=50)
print('OK.')

print('semwait get.')
for k in range(10):
    print(k)
    img.semtimedwait(0, 0.1)
print('OK.')

----
Create
OK.
semwait get.
0
1
The futex facility returned an unexpected error code.
Aborted (core dumped)
```

However... the same in straight C isn't a problem...

```C
#include "ImageStreamIO.h"
#include "ImageStruct.h"

#include <time.h>


int main() {
    char name[] = "asdf_ghjjk";

    IMAGE image;

    uint32_t dims[3] = {2,3,4};

    ImageStreamIO_createIm(&image, name, 2, dims, _DATATYPE_INT16, 1, 50, 0);
    ImageStreamIO_destroyIm(&image);
    ImageStreamIO_createIm(&image, name, 2, dims, _DATATYPE_INT16, 1, 50, 0);
    ImageStreamIO_closeIm(&image);
    ImageStreamIO_openIm(&image, name);


    int sem_idx = ImageStreamIO_getsemwaitindex(&image, 0);

    struct timespec t;

    float timeout_sec = 0.1;

    for (int i = 0; i < 20; i++) {
        printf("sem_timedwait %d...", i);
        clock_gettime(CLOCK_ISIO, &t);
        t.tv_nsec += (long)(timeout_sec * 1000000000L);
        t.tv_sec += t.tv_nsec / 1000000000L;
        t.tv_nsec = t.tv_nsec % 1000000000L;   
        ImageStreamIO_semtimedwait(&image, sem_idx, &t);
        printf("ok.\n");
    }

    return 0;
}
--------
$ ./isio_test 
sem_timedwait 0...ok.
sem_timedwait 1...ok.
sem_timedwait 2...ok.
sem_timedwait 3...ok.
sem_timedwait 4...ok.
sem_timedwait 5...ok.
sem_timedwait 6...ok.
sem_timedwait 7...ok.
sem_timedwait 8...ok.
sem_timedwait 9...ok.
sem_timedwait 10...ok.
sem_timedwait 11...ok.
sem_timedwait 12...ok.
sem_timedwait 13...ok.
sem_timedwait 14...ok.
sem_timedwait 15...ok.
sem_timedwait 16...ok.
sem_timedwait 17...ok.
sem_timedwait 18...ok.
sem_timedwait 19...ok.
```

Any thoughts....?

Unfortunately, this breaks pyMlk, which is fairly mission-critical in a number of spots.
The most obvious is a variety of mismatches between duplicate compiled libraries... I hope I have been careful enough...?

Vince

### PR DESCRIPTION
**Pull request by DasVinch**
I believe this should fix #50 .
@drbitboy let me know if you think there are side effects or if rounding up to 8 should happen in other sections as well.

### CODE REVIEW

**Comment by drbitboy** [comment]
Nice.  This is more or less what I was thinking, and it should do the trick.

Let me ponder some more tomorrow.

**Review by drbitboy — APPROVED** [review]
This should be fine.

I wonder if ```& (~7)``` at the end might be a better choice than ```& (-8)```, but I am pretty sure it does not matter.

**Comment by DasVinch** [comment]
Not gonna lie, I found this on stackoverflow and I was happy about it enough :D

**Comment by a-sevin** [comment]
github copilot suggestion:

```C
// macro to align data to 64-bit boundary
#define ALIGN64(x) (((x) + 7) & ~7)
// macro to align data to 32-bit boundary
#define ALIGN32(x) (((x) + 3) & ~3)
// macro to align data to 16-bit boundary
#define ALIGN16(x) (((x) + 1) & ~1)
```

or
 
```C
// macro to align data to 64-bit boundary
#define ALIGNMENT 8
#define ALIGN(x) (((x) + ALIGNMENT - 1) & ~(ALIGNMENT - 1))
```

**Pull request merged**
