### PR TITLE
Refactor/20230213 drbitboy

### PR DESCRIPTION
**Pull request by drbitboy**
Hi all,

This is the branch (refactor/20230213-drbitboy) where I will be making changes.

I plan to push small commits so to make it easier to review them i.e. one commit at a time.

Not much so far, just fixed the tests.

Brian Carcich

### CODE REVIEW

**Comment by DasVinch** [comment]
Sounds great, thanks!

I'm getting familiar with the PR interface on github, so I'm not sure if I merge/rebase along the way if you'll need to reopen a PR every time of if you can just add commits and reopen this one. We'll see!

**Comment by DasVinch** [comment]
I'm confused... github generated 2 new commit hashes 67b239cb and 22df9329 instead of just cleanly rebasing the `dev` pointer to 10393bc7....
Not sure if by design or I made a mistake. Will try harder next time :).

**Comment by DasVinch** [comment]
Update: on web-based PR rebase, github change the commiter field from @drbitboy to me. This results in a different commit hash... and thus now branches `refactor/20230213-drbitboy` and `dev` are diverged by 2 commits each.

**Comment by drbitboy** [comment]
no problem, I merged that dev back into my repo, and now I have one more commit in here as well LOL.

Okay, they are the same now.

**Comment by drbitboy** [comment]
Hi, I accidentally pushed some changes to **dev** branch, but I did a **git reset --hard**  and restored it to where it was.

I added some tests to this branch **refactor/2023...-drbitboy**; I'll do a PR tomorrow.

**Pull request merged**
